name: Build Docker image

on:
  push:
    branches: master

jobs:
  main:
    name: Docker
    if: github.repository_owner == 'XboxDev'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        image-name: [nxdk, nxdk-debug, nxdk-lto]
        include:
          - image-name: nxdk
            build-args: buildparams=CFLAGS=-O2 CXXFLAGS=-O2
          - image-name: nxdk-debug
            build-args: buildparams=DEBUG=y
          - image-name: nxdk-lto
            build-args: buildparams=LTO=y CFLAGS=-O2 CXXFLAGS=-O2
    steps:
      - name: Clone Tree
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate timestamp
        id: timestamp
        run: echo ::set-output name=timestamp::$(date --rfc-3339=seconds --utc)
      - name: Generate tags
        id: tags
        run: |
          DOCKER_IMAGE=xboxdev/${{ matrix.image-name }}
          TAGS="${DOCKER_IMAGE}:latest"
          TAGS="$TAGS,${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
          TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:latest"
          TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: ${{ matrix.build-args }}
          platforms: linux/amd64,linux/386
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}
